# Generated by Django 2.0.5 on 2019-04-09 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AskQuestion',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('questionTitle', models.CharField(max_length=100)),
                ('questionText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('answerid', models.AutoField(primary_key=True, serialize=False)),
                ('answerText', models.TextField()),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborate.AskQuestion')),
            ],
        ),
    ]
