# Generated by Django 2.0.5 on 2019-04-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='askquestion',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
