# Generated by Django 2.0.5 on 2019-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0003_questionanswer_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='unlike',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
