# Generated by Django 2.0.5 on 2019-04-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0004_auto_20190417_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='like',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='unlike',
        ),
    ]
