# Generated by Django 2.0.5 on 2019-04-18 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborate', '0005_auto_20190417_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
