# Generated by Django 2.0.5 on 2019-05-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0006_questionanswer_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='likes',
        ),
    ]
