# Generated by Django 2.0.5 on 2019-05-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0007_auto_20190501_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
